spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo_1_bdd_oo2_2020?serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false

